spring:
  application:
    name: spring-config-server
  profiles:
    active: local,development,production
  cloud:
    config:
      server:
        git:
          uri: https://github.com/baloz/config-server.git
          default-label: main
          search-paths: spring-config/
server:
  port: 8888
management:
  security:
    enabled: false